### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Whew, that was lots of work, but I finally got the CI to turn green!

A few weird things to note:

1. I had to add this: https://github.com/conda-forge/gmsh-feedstock/blob/a5a21fce42fb28052e9637baf3f6c0305712bf8e/recipe/build_gmsh.sh#L10-L14
   in order to avoid errors like
    ```
    [ 56%] Building C object CMakeFiles/shared.dir/contrib/metis/GKlib/string.c.o
    /home/conda/feedstock_root/build_artifacts/gmsh-packages_1755213966477/work/contrib/metis/GKlib/string.c: In function 'gk_str2time':
    /home/conda/feedstock_root/build_artifacts/gmsh-packages_1755213966477/work/contrib/metis/GKlib/string.c:506:7: error: implicit declaration of function 'strptime'; did you mean 'strftime'? [-Wimplicit-function-declaration]
      506 |   if (strptime(str, "%m/%d/%Y %H:%M:%S", &time) == NULL)
          |       ^~~~~~~~
          |       strftime
    make[2]: *** [CMakeFiles/shared.dir/build.make:6561: CMakeFiles/shared.dir/contrib/metis/GKlib/string.c.o] Error 1
    ```
    I'm not really proficient in C, so this was entirely LLM-assisted.
2. Since rerendering, the separate builds on `linux-64` for occt 7.7.2 and 7.8.1 are now both being built by a single runner. It seems to compile successfully, producing two separate artifacts. Maybe this is a conda-smithy bug?

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

File: recipe/ensure_python_gmsh.py
Comment (h-vetinari) [inline recipe/ensure_python_gmsh.py:1]: I think this is overengineered. We can build `python-gmsh` for several occt versions, or rather, if we do the dependencies right, those builds will have the same hash and only be uploaded once.

File: recipe/meta.yaml [hunk 1]
```diff
@@ -76,19 +80,25 @@ outputs:
   - name: python-gmsh
     build:
       noarch: python
-      skip: true  # [build_platform != target_platform]
-    script: install_python.sh  # [not win]
-    script: install_python.bat  # [win]
+      skip: true  # [build_platform != target_platform or target_platform != "linux-64" or occt != "7.8.1"]
```
Comment (h-vetinari) [inline recipe/meta.yaml:83]: I would leave out the occt condition here. It'll become a pain to keep up-to-date (c.f. #105, #106)
```suggestion
      skip: true  # [build_platform != target_platform or target_platform != "linux-64"]
```

File: recipe/meta.yaml [hunk 2]
```diff
@@ -76,19 +80,25 @@ outputs:
...
+    script: install_python_module.py
     requirements:
+      host:
+        - python {{ python_min }}
       run:
         # this should pin build number as well,
         # but we can't use exact=True while this is noarch
         - {{ pin_subpackage("gmsh", max_pin="x.x.x") }}
```
Comment (h-vetinari) [inline recipe/meta.yaml:91]: The simplest way to do this IMO would be to just depend on `gmsh` here more generically. During each build process, this will be satisfied by the local artefacts, but the `python-gmsh` builds for different occt versions will have exactly the same dependencies (and thus build string hashes), and so their uploads should actually coincide (i.e. the second one gets ignored if an artefact with exactly matching `package-version-buildstring` exists already).
```suggestion
      run:
        - gmsh {{ version }} *_{{ PKG_BUILDNUM }}
```

**Comment by h-vetinari** [comment]
@maresb @conda-forge/gmsh, this should now be ready, PTAL! :)

In removing @maresb's scripts, I've also undone the fix for the pip metadata; I don't want this PR to struggle over the scope of these things, as we really need to unblock the occt migration, which is stuck on gmsh and causing a bunch of issues elsewhere.

The best thing would be for upstream gmsh to have an installation script that correctly generates the respective pip metadata; I don't mind patching this in, but:
* keep it simple & test with `pip check`
* no complicated occt version-matching logic
* not custom GHA workflows

In any case, all that is material for a separate PR, and this should IMO just be a stepping stone to getting to #105 / #106

**Comment by h-vetinari** [comment]
> Can you please apply [b9e9c99](https://github.com/conda-forge/gmsh-feedstock/commit/b9e9c990165977a9a682d41f157984269791213f) that you forced pushed over?

Sure, apologies. I had applied all your suggestions, but Github UI was buggy and only actually applied 3 out of 5. That's why I had force-pushed, and didn't notice your push in the meantime.

**Comment by h-vetinari** [comment]
I think this should be ready now? @conda-forge/gmsh

**Comment by h-vetinari** [comment]
Thank you!
